services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_data:/data
      - ./database:/import
    networks:
      - game-soul-network

  # backend:
  #   build:
  #     context: ./game-soul-backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - neo4j
  #   environment:
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=password
  #     - HOST=0.0.0.0
  #     - PORT=3001
  #     - ENVIRONMENT=development
  #     - FRONTEND_URL=http://localhost:3000
  #   networks:
  #     - game-soul-network

  # Puedes descomentarlo cuando tengas el frontend listo
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - game-soul-network

volumes:
  neo4j_data:

networks:
  game-soul-network:
    driver: bridge