services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_data:/data
      - ./database:/import
    networks:
      - game-soul-network

# Backend (opcional - para desarrollo se puede ejecutar con Maven)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: game-soul-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      - game-soul-network
    # Solo descomentar si quieren usar Docker para el backend también

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:

networks:
  game-soul-network:
    driver: bridge